# Generated by Django 5.2.7 on 2025-10-20 16:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('production', 'Production'), ('consumption', 'Consommation')], max_length=12)),
                ('points', models.JSONField(help_text='Liste de 96 floats (24h, pas 15 min)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du projet')),
                ('phase', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='annual_consumption_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='annual_production_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='daily_consumption_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='daily_production_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='data_mode',
            field=models.CharField(choices=[('timeseries_csv', 'Série 15-min via CSV'), ('profile_based', 'Basé sur profil(s)')], default='timeseries_csv', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='timeseries_file',
            field=models.FileField(blank=True, null=True, upload_to='timeseries/'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_factor', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='core.member')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_profiles', to='core.profile')),
            ],
            options={
                'unique_together': {('member', 'profile')},
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
