# Generated by Django 5.2.7 on 2025-10-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='annual_consumption_kwh',
        ),
        migrations.RemoveField(
            model_name='member',
            name='annual_production_kwh',
        ),
        migrations.RemoveField(
            model_name='member',
            name='daily_consumption_kwh',
        ),
        migrations.RemoveField(
            model_name='member',
            name='daily_production_kwh',
        ),
        migrations.RemoveField(
            model_name='member',
            name='data_mode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kind',
        ),
        migrations.AddField(
            model_name='profile',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='profile_graphs/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='utility',
            field=models.CharField(blank=True, max_length=200, verbose_name='Utility'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.JSONField(help_text='List of 96 floats (24h, 15 min interval)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Project name'),
        ),
    ]
