# Generated by Django 5.2.7 on 2025-10-20 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_member_annual_consumption_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='annual_consumption_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='annual_production_kwh',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='data_mode',
            field=models.CharField(choices=[('timeseries_csv', 'Série 15-min via CSV'), ('profile_based', 'Basé sur profil(s)')], default='timeseries_csv', max_length=20),
        ),
    ]
