# Generated by Django 5.2.7 on 2025-10-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_annual_consumption_kwh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='scale_factor',
        ),
    ]
