# Generated by Django 5.2.7 on 2025-11-09 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_memberprofile_scale_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="current_fixed_annual_fee_eur",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Current fixed annual fee (€)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="current_unit_price_eur_per_kwh",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Current unit price (€/kWh)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="injected_energy_kwh",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Injected energy (kWh)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="injection_price_eur_per_kwh",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Injection price (€/kWh)",
            ),
        ),
    ]
