# Generated by Django 5.2.7 on 2025-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_memberprofile_scale_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="timeseries_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[("consumption", "Consommation"), ("production", "Production")],
                default="consumption",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="points",
            field=models.JSONField(
                help_text="List of quarter-hour values for a full year"
            ),
        ),
    ]
