# Generated by Django 5.2.7 on 2025-11-09 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_member_timeseries_metadata_profile_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="current_fixed_fee_eur",
            field=models.FloatField(
                default=0.0,
                help_text="Partie fixe annuelle de la facture actuelle (€/an).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="current_unit_price_eur_per_kwh",
            field=models.FloatField(
                default=0.25,
                help_text="Prix unitaire actuel payé au fournisseur (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="injection_annual_kwh",
            field=models.FloatField(
                default=0.0,
                help_text="Energie annuelle injectée sur le réseau (kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="injection_unit_price_eur_per_kwh",
            field=models.FloatField(
                default=0.05,
                help_text="Tarif de rachat pour l'injection (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.CreateModel(
            name="StageThreeScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "community_price_eur_per_kwh",
                    models.FloatField(
                        blank=True,
                        help_text="Prix cible de l'énergie communautaire (€/kWh).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "price_min_eur_per_kwh",
                    models.FloatField(
                        blank=True,
                        help_text="Borne minimum pour optimiser le prix communautaire (€/kWh).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "price_max_eur_per_kwh",
                    models.FloatField(
                        blank=True,
                        help_text="Borne maximum pour optimiser le prix communautaire (€/kWh).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "price_step_eur_per_kwh",
                    models.FloatField(
                        default=0.005,
                        help_text="Pas utilisé lors de l'exploration du prix communautaire.",
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                (
                    "default_share",
                    models.FloatField(
                        default=1.0,
                        help_text="Part de consommation couverte par défaut par l'énergie communautaire (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "coverage_cap",
                    models.FloatField(
                        default=1.0,
                        help_text="Part maximale pouvant être couverte (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "community_fixed_fee_total_eur",
                    models.FloatField(
                        default=0.0,
                        help_text="Coût fixe annuel de la communauté à répartir (€/an).",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "community_per_member_fee_eur",
                    models.FloatField(
                        default=0.0,
                        help_text="Frais annuels individuels (€/an) pour les membres participants.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "fee_allocation",
                    models.CharField(
                        choices=[
                            ("all_members", "Répartition égale (tous les membres)"),
                            ("participants", "Répartition égale (participants)"),
                            (
                                "consumption",
                                "Proportionnelle à l'énergie communautaire",
                            ),
                        ],
                        default="participants",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage3_scenarios",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="StageThreeScenarioMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_override",
                    models.FloatField(
                        blank=True,
                        help_text="Valeur utilisée par défaut pour ce membre (0-1).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "min_share",
                    models.FloatField(
                        blank=True,
                        help_text="Bornes minimales pour les optimisations (0-1).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "max_share",
                    models.FloatField(
                        blank=True,
                        help_text="Bornes maximales pour les optimisations (0-1).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage3_settings",
                        to="core.member",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_settings",
                        to="core.stagethreescenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "member__name"],
                "unique_together": {("scenario", "member")},
            },
        ),
    ]
