# Generated by Django 5.2.7 on 2025-11-10 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_member_current_fixed_fee_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagethreescenario",
            name="community_injection_price_eur_per_kwh",
            field=models.FloatField(
                blank=True,
                help_text="Tarif interne pour rémunérer l'injection (€/kWh). Laisser vide pour utiliser le tarif membre.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="stagethreescenario",
            name="community_variable_fee_eur_per_kwh",
            field=models.FloatField(
                default=0.0,
                help_text="Frais variables appliqués à chaque kWh communautaire (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="stagethreescenario",
            name="tariff_context",
            field=models.CharField(
                choices=[
                    ("community_grid", "Communauté via réseau public"),
                    ("community_same_site", "Communauté même bâtiment"),
                    ("traditional", "Facture fournisseur de référence"),
                ],
                default="community_grid",
                help_text="Cadre réglementaire utilisé pour expliquer les composantes de coût.",
                max_length=40,
            ),
        ),
    ]
