# Generated by Django 5.2.7 on 2025-11-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_stagethreescenario_community_injection_price_eur_per_kwh_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StageTwoScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("iterations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage2_scenarios",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
