# Generated by Django 5.2.7 on 2025-12-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_stage3_simplification"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("source_file", models.FileField(upload_to="ingestion_sources/")),
                ("generated_file", models.FileField(upload_to="ingestion_generated/")),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "name"],
            },
        ),
    ]
