# Generated by Django 5.2.7 on 2025-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ingestiontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestiontemplate",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

