# Generated by Django 5.2.7 on 2025-12-03 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_dataset_remove_member_data_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="current_fixed_fee_eur",
        ),
        migrations.RemoveField(
            model_name="member",
            name="current_unit_price_eur_per_kwh",
        ),
        migrations.RemoveField(
            model_name="member",
            name="injection_annual_kwh",
        ),
        migrations.RemoveField(
            model_name="member",
            name="injection_unit_price_eur_per_kwh",
        ),
        migrations.AddField(
            model_name="member",
            name="access_fee_eur_per_kwh",
            field=models.FloatField(
                default=0.0,
                help_text="Redevance d'accès (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="distribution_tariff_eur_per_kwh",
            field=models.FloatField(
                default=0.05,
                help_text="Tarif de distribution (DSO) (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="energy_contribution_eur_per_kwh",
            field=models.FloatField(
                default=0.0,
                help_text="Contribution énergie (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="green_support_eur_per_kwh",
            field=models.FloatField(
                default=0.01,
                help_text="Soutien énergie verte (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="injection_price_eur_per_kwh",
            field=models.FloatField(
                default=0.05,
                help_text="Tarif d'injection (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="special_excise_eur_per_kwh",
            field=models.FloatField(
                default=0.0,
                help_text="Accise spéciale (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="supplier_energy_price_eur_per_kwh",
            field=models.FloatField(
                default=0.25,
                help_text="Prix énergie facturé par le fournisseur (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="transport_tariff_eur_per_kwh",
            field=models.FloatField(
                default=0.02,
                help_text="Tarif de transport (TSO) (€/kWh).",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
