# Generated by Django 5.2.7 on 2025-12-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_member_current_fixed_fee_eur_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StageThreeScenarioMember",
        ),
    ]
